blank_issues_enabled: false
contact_links:
  - name: Homebridge Discord Channel for Roomba2
    url: https://discord.gg/8fpZA4S
    about: Please ask and answer questions here.
  - name: homebridge-roomba2 - Pull Requests
    url: https://github.com/homebridge-plugins/homebridge-roomba2/pulls
    about: Please report security vulnerabilities here.
