blank_issues_enabled: false
contact_links:
  - name: Homebridge Discord Channel for Roomba
    url: https://discord.gg/8fpZA4S
    about: Please ask and answer questions here.
  - name: homebridge-roomba - Pull Requests
    url: https://github.com/homebridge-plugins/homebridge-roomba/pulls
    about: Please report security vulnerabilities here.
